AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless_api

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  Serverless:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.serverless.api.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: /Users/Anuwat_K/Desktop/Working/serverless_api/target/serverless.jar
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        ApplicationGET:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: get
        ApplicationPOST:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: post

Outputs:
  ServerlessApi:
    Description: URL for Application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: ServerlessApi